### ISSUE TITLE
Tv Guide clicking on the programme the poster is cut in half

### ISSUE THREAD

**Issue by denz2** [EmbySupport/Emby.WMC.UI#10]
![Screenshot 2023-09-06 130746](https://github.com/EmbySupport/Emby.WMC.UI/assets/16771401/9686b5e5-acea-4b66-803e-9bc692ba9f1c)

**Comment by softworkz** [comment]
Yes, I had seen it. It's even in the video, but it was too late to fix it in-time.

Thanks for reporting!

**Comment by softworkz** [comment]
Fixed in https://github.com/EmbySupport/Emby.WMC.UI/releases/tag/0.101.0
