### ISSUE TITLE
Video Player Back Button Behavior: Broken 

### ISSUE THREAD

**Issue by TMCsw** [EmbySupport/Emby.WMC.UI#13]
When setting this it will always revert back to blank, next time playback settings is entered (all clients tried).
Even Worse, play back will always keep playing in the background (very annoying to me):
![image](https://github.com/EmbySupport/Emby.WMC.UI/assets/77761397/c93310ce-ec7f-45d8-b905-6f7047b7b242)

**Comment by SikSlayer** [comment]
Just tested it in everything I could. Same issue for me.

**Comment by softworkz** [comment]
This setting should be hidden and must not have any effect, so that's a bug.

Thanks for reporting!

**Comment by softworkz** [comment]
As for videos keep playing in background - that's WMC behavior. You can always press "Stop" on the remote control or press the "Stop" button at the bottom right to stop playback.

Maybe a bit unusual for Emby users, but you also see the video playing as miniature wherever you go.

**Comment by softworkz** [comment]
Fixed in https://github.com/EmbySupport/Emby.WMC.UI/releases/tag/0.101.0
