### ISSUE TITLE
Unable to load photo sub folders

### ISSUE THREAD

**Issue by vvicked** [EmbySupport/Emby.WMC.UI#14]
My photos are organized by folder year and sub folders.  For example:
YearFolderName/SubFolder1/jpgs
YearFolderName/SubFolder2/jpgs
YearFolderName/SubFolder3/jpgs

When I launch the photos link, it will display all of my year folders (including thumbs).  However, when I enter a year sub folder, all I get is spinning.

![image](https://github.com/EmbySupport/Emby.WMC.UI/assets/6483724/0db92a77-c63f-4c75-9650-c3c2704bb293)

**Comment by softworkz** [comment]
Thanks for the report!

A spinning wheel which doesn't go away quickly (and which is not in a context of starting playback) is a strong indication for a bug.
I'll try to repro next week. Thanks again.

**Comment by vvicked** [comment]
BTW, great work so far this is so nostalgic.  I just tested movie folder view and it has the same issue.  I can view my movie category folders but cannot see anything when I try to view the folder contents.

**Comment by vvicked** [comment]
Thank you.  Not only did you fix the issue I reported but you also improved something that the release version of emby doesnt do right.  The small folder and image icon overlays re correctly displaying on thumbnails, no matter what folder depth I am browsing.

**Comment by vvicked** [comment]
I confirmed the issue is fixed 0.101.0 web ui.

**Comment by softworkz** [comment]
Thanks a lot for reporting and validating!
