### ISSUE TITLE
You can’t get there from here? (fire stick 4k max (others?))

### ISSUE THREAD

**Issue by TMCsw** [EmbySupport/Emby.WMC.UI#18]
I can’t find a way to go up from ‘shows’ to ‘filters‘ 
![image](https://github.com/EmbySupport/Emby.WMC.UI/assets/77761397/2afffd57-592c-4372-b5e4-972cc0f75fed)

Is it because this is missing for “TV Shows”? And why are these options missing?
![image](https://github.com/EmbySupport/Emby.WMC.UI/assets/77761397/1c0506a6-95e2-491a-8764-e9a419159b46)

**Comment by softworkz** [comment]
Fixed in 0.103.0.

> And why are these options missing?

Probably this functionality isn't available in the core client. 
But play-all or shuffle doesn't make much sense anyway for tv shows, I suppose.

Thanks a lot for reporting!

**Comment by TMCsw** [comment]
Yes I can now get there!
(actually I only care to get there for the ‘all/unplayed filter’) 

“But play-all or shuffle doesn't make much sense anyway for tv shows, I suppose.”
It does make sense shows that don’t have ‘real’ plot to fallow? No?

**Comment by softworkz** [comment]
> It does make sense shows that don’t have ‘real’ plot to fallow? No?

But at this position it would mean to play/shuffle everything from all shows, not like from the selected show (because when you move there, no show is selected anymore.

**Comment by TMCsw** [comment]
sorry I meant to reply earlier…
In the case shown I’m in a library that contains nothing but old SD TV Series (OTA Recordings) so these options should be available.
I know that is not always the case but the same could be said for a movie library that contains only a movie ‘series’ say something like ‘Star Trek’,  ‘Star Wars’, ‘Harry Potter’…
Let the user choose to use or not.

**Comment by softworkz** [comment]
The core app doesn't allow this, so I'd need to start extra work on this
Please request this for the core app in the Emby forums. Thanks.
