### ISSUE TITLE
Live tv spinner disappears too quickly 

### ISSUE THREAD

**Issue by denz2** [EmbySupport/Emby.WMC.UI#21]
In Australia it takes a long time for live tv to start with emby clients in general maybe 6 or 7 seconds and the spinner disappears after few seconds and you are just waiting there thinking have you pressed it.  WMC starts Live tv within a second on the pc that runs emby server even though it is old it still has tricks up its sleve that others can't replicate. If the live tv could start in half the time it would be ideal solution.

**Comment by softworkz** [comment]
With TVnext, channel switching will be on-par with WMC.

**Comment by denz2** [comment]
Had to search to find out what is TVnext. When can we try that ? It is the last thing still holding me to wmc.

**Comment by softworkz** [comment]
One of the forum topics is here: https://emby.media/community/index.php?/topic/115305-to-complain-about-lacking-tvnext-progress/
Thanks
