### ISSUE TITLE
Current Android WMC UI beta already out of date

### ISSUE THREAD

**Issue by SikSlayer** [EmbySupport/Emby.WMC.UI#22]
![Screenshot_20231022-092548](https://github.com/EmbySupport/Emby.WMC.UI/assets/8442046/d6d1e733-4bc2-4afd-86bb-efae11b5b153)

This is on the most recent version that's not even as old as some past beta versions were when they were the current version.

Why does this even have a built in expiration function?? 🤦🏾‍♂️🤷🏾‍♂️

**Comment by softworkz** [comment]
New version will be there in the next 30 minutes!

**Comment by SikSlayer** [comment]
It's happened again.

**Comment by softworkz** [comment]
Sorry for the inconvenience. New version is underway!
