### ISSUE TITLE
Digital Everywhere FireDTV Live-TV card support in WMC ?

### ISSUE THREAD

**Issue by Peerke123** [EmbySupport/Emby.WMC.UI#23]
In Europe (especially), the Digital Everywhere FiredTV cards (also called: FloppyDTV, see http://digital-everywhere.digitaldevices.de/) for DVB-C (and DVB-S2) used to be very popular for MCE usages, especially as they simulated DVB-C into DVB-T which MCE supported. 

How can these FireDTV cards being used in WMC ? 

Thnx, Peter

**Comment by LukePulverenti** [comment]
Hi, that is a general Emby request that should be filed in the Emby Community. It is not something that is theme-specific. Thanks.

**Comment by Peerke123** [comment]
Dear Luke, you are 100% right, I still have to get used to the WMC gui on top of Emby and thus the functionality seperation between WMC gui <> Emby....oeps, sorry.

I'll enter it as a generakl Emby live-TV request.

Thnx. **Peter**
