### ISSUE TITLE
Translations - Dutch (Netherlands+Flemish part of Belgium)

### ISSUE THREAD

**Issue by Peerke123** [EmbySupport/Emby.WMC.UI#24]
Testing WMC as a Dutch (Netherlands) citizen, I recognise that several items in WMC-beta are still English but sometimes also already in the Dutch language...

Any idea of the status of these (Dutch) translations ?

Grtz, Peter

**Comment by softworkz** [comment]
Hi, you can join the translation team and help adding Dutch translations here: http://translate.emby.media/collaboration/project?id=191312

Thanks,
softworkz

**Comment by Peerke123** [comment]
Dear Softworkz,  

 

Translated WMC into The Netherlands/Dutch language (it took approx. 3 hours moostly by looking it up in the good-old MCE), but as this translation tool doesn’t show the context or ‘the real environment’ (of WMC), I’m not sure that everything is ok…..

 

Thanks & best regards,

Peter Nent

Van: softworkz ***@***.***> 
Verzonden: vrijdag 27 oktober 2023 08:39
Aan: EmbySupport/Emby.WMC.UI ***@***.***>
CC: Peerke123 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [EmbySupport/Emby.WMC.UI] Translations - Dutch (Netherlands+Flemish part of Belgium) (Issue #24)

 

Hi, you can join the translation team and help adding Dutch translations here: http://translate.emby.media/collaboration/project?id=191312

Thanks,
softworkz

**Comment by softworkz** [comment]
Thanks Peter! A new version 105 including your translations will be up in the next few hours!

**Comment by Peerke123** [comment]
Can't find my translation....many items are still in English....

Help ...
Grtz. Peter

**Comment by softworkz** [comment]
Which language do you set under App Settings > UserName > Display > Language?

**Comment by softworkz** [comment]
Peter?

**Comment by Peerke123** [comment]
Checked this matter, the settings are: Dutch language (before I used 'automatically' with same results): I can't find my into Dutch (= Netherlands) translated words....
Grtz. Peter

**Comment by softworkz** [comment]
Sorry, I had forgotten to activate it. The new version from yesterday shows your translations:

![image](https://github.com/EmbySupport/Emby.WMC.UI/assets/4985349/37a90a14-63a1-49cb-9f08-f847ce7189ba)
