### ISSUE TITLE
In tv recordings show description and details are cut off

### ISSUE THREAD

**Issue by denz2** [EmbySupport/Emby.WMC.UI#29]
Currently in tv recordings the description is being cut off due to large space taken by the logo. I think having a logo is unnecessary when there is two rows of recordings.  On one row it would fit and hopefully one day we get that.  

![thumbnail_IMG_3816](https://github.com/EmbySupport/Emby.WMC.UI/assets/16771401/18d7669c-4dd9-4ead-8156-6dd41d000829)
![thumbnail_IMG_3815](https://github.com/EmbySupport/Emby.WMC.UI/assets/16771401/e80f0d03-80e9-4e4d-86de-f85cdd25982f)

Well done on your amazing work my family are now using emby a bit more tried before it was few minutes and back they go to wmc. But so far it has been very positive. The constant nag is the slow speed of channel changing but on the positive we don't have to restart wmc some nights three or four times as WMC freezes.

**Comment by softworkz** [comment]
> Well done on your amazing work my family are now using emby a bit more tried before it was few minutes and back they go to wmc. But so far it has been very positive. 

Thanks for the feedback!

> The constant nag is the slow speed of channel changing

Just keep nagging :-)  (https://emby.media/community/index.php?/topic/115305-to-complain-about-lacking-tvnext-progress)


I've added this to be tracked by https://github.com/EmbySupport/Emby.WMC.UI/issues/2 and the list maintained there, so it won't be forgotten. 
View customizations will allow to change all those things like showing logos or not and showing single-row or two rows.
