### ISSUE TITLE
Subtitle Search is not Available

### ISSUE THREAD

**Issue by Epic-dog** [EmbySupport/Emby.WMC.UI#3]
Not sure if I missed something but when watching a film or a TV show, I do not see any option to select/download or pick subtitles in any of the options or menus.
![image](https://github.com/EmbySupport/wmc-theme-test/assets/77271391/63b81426-25d8-44fe-a905-493bd2edb1be)

Even from the cog menu

![image](https://github.com/EmbySupport/wmc-theme-test/assets/77271391/6d9224d1-3d62-4bb1-976e-f3f4277fb37b)

or even the info options
![image](https://github.com/EmbySupport/wmc-theme-test/assets/77271391/c0943db5-eeed-4e4b-af6f-dd2a11022998)

So for a user this looks to be missing.

** Just to Add I mean the option to download Subtitles if they are missing, for other media the icon does show.  **

In emby when playing media you see the below as an option 

![image](https://github.com/EmbySupport/wmc-theme-test/assets/77271391/dd8149f1-1c8e-4734-a3b9-c36925223ee9)

I do not see this in WMC, so I am unable to download missing subtitles. Hopefully that makes sense :D

**Comment by softworkz** [comment]
Fixed in 0.102.0

**Comment by softworkz** [comment]
Closing. Please comment in case there are any remaining issues.
Thanks for reporting!
