### ISSUE TITLE
[Feature] Show recordings in a single row

### ISSUE THREAD

**Issue by denz2** [EmbySupport/Emby.WMC.UI#8]
Well done on the vast amount of work you did.

![Screenshot 2023-09-06 130000](https://github.com/EmbySupport/Emby.WMC.UI/assets/16771401/cd7c7509-fcc5-4790-897c-9fc41e744746)

In WMC you can change the look to show recordings in multiple rows how it is done here but also single row. I prefer single row

**Comment by softworkz** [comment]
I've added this to the Epic issue for view customization: https://github.com/EmbySupport/Emby.WMC.UI/issues/2

I'm closing this in favor of the Epic issue, but it won't be forgotten.

Thanks
