### ISSUE TITLE
Can the gap between the channel number and logo be reduced

### ISSUE THREAD

**Issue by denz2** [EmbySupport/Emby.WMC.UI#9]
Currently there is a big gap between channel number and channel logo it would be better if it was smaller.

**Comment by softworkz** [comment]
Yea, IIRC, the distance is the same as for "Name + Logo" which isn't right.

Thanks for reporting!

**Comment by softworkz** [comment]
Fixed in https://github.com/EmbySupport/Emby.WMC.UI/releases/tag/0.101.0
